ASide:
  - Room: "01"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "right_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "02"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "03"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "04"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: out
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "up_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "04b"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: in
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
        InternalEdges:
          - To: "left_0"
            ReqIn:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
  - Room: "05"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: out
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "06"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: out
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "down_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "07"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: in
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "down_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: out
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "08"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "up_3"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: out
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
    InternalEdges:
      - To: "up_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "09"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "right_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "10"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: out
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "up_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "10b"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: inout
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
        InternalEdges:
          - To: "up_0"
            ReqIn:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
  - Room: "11"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "right_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "11b"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
