ASide:
  - Room: "c-02"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: out
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "up_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-03"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "right_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "c-04"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-05"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-06"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-07"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-08"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: out
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: easy
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_1"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-09"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: out
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "up_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-10"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "right_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "c-11"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
    Core:
      All: hot
  - Room: "c-12"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-13"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: out
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "up_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-14"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-15"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-16"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    Core:
      All: hot
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "c-17"
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: in
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Tweaks:
      - ID: 509
        Update:
          Remove: true
      - Name: "blackGem"
        Update:
          Add: true
          X: 248
          Y: 24
    Core:
      All: hot
