ASide:
  - Room: "a-01"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "up_4"
        Holes:
          - Side: Up
            Idx: 4
            Kind: none
      - Room: "up_5"
        Holes:
          - Side: Up
            Idx: 5
            Kind: none
      - Room: "up_6"
        Holes:
          - Side: Up
            Idx: 6
            Kind: none
      - Room: "up_7"
        Holes:
          - Side: Up
            Idx: 7
            Kind: none
      - Room: "up_8"
        Holes:
          - Side: Up
            Idx: 8
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "down_5"
        Holes:
          - Side: Down
            Idx: 5
            Kind: none
      - Room: "down_6"
        Holes:
          - Side: Down
            Idx: 6
            Kind: none
      - Room: "down_7"
        Holes:
          - Side: Down
            Idx: 7
            Kind: none
      - Room: "down_8"
        Holes:
          - Side: Down
            Idx: 8
            Kind: none
      - Room: "down_9"
        Holes:
          - Side: Down
            Idx: 9
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "left_3"
        Holes:
          - Side: Left
            Idx: 3
            Kind: none
      - Room: "left_4"
        Holes:
          - Side: Left
            Idx: 4
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: out
      - Room: "right_3"
        Holes:
          - Side: Right
            Idx: 3
            Kind: none
    InternalEdges:
      - To: "right_2"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "a-02"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "up_4"
        Holes:
          - Side: Up
            Idx: 4
            Kind: none
      - Room: "up_5"
        Holes:
          - Side: Up
            Idx: 5
            Kind: none
      - Room: "up_6"
        Holes:
          - Side: Up
            Idx: 6
            Kind: none
      - Room: "up_7"
        Holes:
          - Side: Up
            Idx: 7
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "down_5"
        Holes:
          - Side: Down
            Idx: 5
            Kind: none
      - Room: "down_6"
        Holes:
          - Side: Down
            Idx: 6
            Kind: none
      - Room: "down_7"
        Holes:
          - Side: Down
            Idx: 7
            Kind: none
      - Room: "down_8"
        Holes:
          - Side: Down
            Idx: 8
            Kind: none
      - Room: "down_9"
        Holes:
          - Side: Down
            Idx: 9
            Kind: none
      - Room: "down_10"
        Holes:
          - Side: Down
            Idx: 10
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "left_3"
        Holes:
          - Side: Left
            Idx: 3
            Kind: inout
        InternalEdges:
          - To: "right_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "right_2"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_4"
        Holes:
          - Side: Left
            Idx: 4
            Kind: none
      - Room: "left_5"
        Holes:
          - Side: Left
            Idx: 5
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: out
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: out
    InternalEdges:
      - To: "left_3"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "a-02-b"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "up_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: inout
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "left_3"
        Holes:
          - Side: Left
            Idx: 3
            Kind: none
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
        InternalEdges:
          - To: "up_0"
            ReqIn:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "up_1"
            ReqIn:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
  - Room: "a-03"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "up_4"
        Holes:
          - Side: Up
            Idx: 4
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "down_5"
        Holes:
          - Side: Down
            Idx: 5
            Kind: none
      - Room: "down_6"
        Holes:
          - Side: Down
            Idx: 6
            Kind: none
      - Room: "down_7"
        Holes:
          - Side: Down
            Idx: 7
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: inout
        InternalEdges:
          - To: "right_2"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: out
      - Room: "right_3"
        Holes:
          - Side: Right
            Idx: 3
            Kind: none
    InternalEdges:
      - To: "left_1"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "a-04"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: inout
        InternalEdges:
          - To: "left_2"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "up_3"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_2"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: none
      - Room: "right_3"
        Holes:
          - Side: Right
            Idx: 3
            Kind: none
      - Room: "right_4"
        Holes:
          - Side: Right
            Idx: 4
            Kind: none
      - Room: "right_5"
        Holes:
          - Side: Right
            Idx: 5
            Kind: none
    InternalEdges:
      - To: "left_2"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "a-05"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "left_3"
        Holes:
          - Side: Left
            Idx: 3
            Kind: none
      - Room: "left_4"
        Holes:
          - Side: Left
            Idx: 4
            Kind: inout
        InternalEdges:
          - To: "right_2"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_5"
        Holes:
          - Side: Left
            Idx: 5
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: out
      - Room: "right_3"
        Holes:
          - Side: Right
            Idx: 3
            Kind: none
      - Room: "right_4"
        Holes:
          - Side: Right
            Idx: 4
            Kind: none
      - Room: "right_5"
        Holes:
          - Side: Right
            Idx: 5
            Kind: none
      - Room: "right_6"
        Holes:
          - Side: Right
            Idx: 6
            Kind: none
    InternalEdges:
      - To: "left_4"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "a-06"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "down_5"
        Holes:
          - Side: Down
            Idx: 5
            Kind: none
      - Room: "down_6"
        Holes:
          - Side: Down
            Idx: 6
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
          - To: "right_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: out
    InternalEdges:
      - To: "left_1"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "a-08"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
        InternalEdges:
          - To: "left_0"
            ReqIn:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
