ASide:
  - Room: "a_02"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
  - Room: "a_03"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: inout
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: none
  - Room: "a_04"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_1"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
  - Room: "a_05"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
  - Room: "a_06"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
  - Room: "a_07"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
  - Room: "a_08"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "left_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: expert
  - Room: "a_09"
    Subrooms:
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: in
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: in
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Tweaks:
      - ID: 287
        Update:
          Remove: true
      - Name: "blackGem"
        Update:
          Add: true
          X: 160
          Y: 120
    Core:
      All: hot
