ASide:
  - Room: "1"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "down_5"
        Holes:
          - Side: Down
            Idx: 5
            Kind: none
      - Room: "down_6"
        Holes:
          - Side: Down
            Idx: 6
            Kind: none
      - Room: "down_7"
        Holes:
          - Side: Down
            Idx: 7
            Kind: none
      - Room: "down_8"
        Holes:
          - Side: Down
            Idx: 8
            Kind: none
      - Room: "down_9"
        Holes:
          - Side: Down
            Idx: 9
            Kind: none
      - Room: "down_10"
        Holes:
          - Side: Down
            Idx: 10
            Kind: none
      - Room: "down_11"
        Holes:
          - Side: Down
            Idx: 11
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: zero
                  Difficulty: normal
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "2"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "down_1"
        Holes:
          - Side: Down
            Idx: 1
            Kind: none
      - Room: "down_2"
        Holes:
          - Side: Down
            Idx: 2
            Kind: none
      - Room: "down_3"
        Holes:
          - Side: Down
            Idx: 3
            Kind: none
      - Room: "down_4"
        Holes:
          - Side: Down
            Idx: 4
            Kind: none
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: inout
        InternalEdges:
          - To: "right_2"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
      - Room: "left_3"
        Holes:
          - Side: Left
            Idx: 3
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: none
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: out
      - Room: "right_3"
        Holes:
          - Side: Right
            Idx: 3
            Kind: none
      - Room: "right_4"
        Holes:
          - Side: Right
            Idx: 4
            Kind: none
    InternalEdges:
      - To: "left_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "4"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: none
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: inout
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: none
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: inout
        InternalEdges:
          - To: "down_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "strawberry_0"
        Collectables:
          - Idx: 0
        InternalEdges:
          - To: "down_0"
            ReqIn:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
    InternalEdges:
      - To: "left_1"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: zero
              Difficulty: easy
  - Room: "5"
    CelesteRandomizerHelper: true
    Subrooms:
      - Room: "up_0"
        Holes:
          - Side: Up
            Idx: 0
            Kind: in
        InternalEdges:
          - To: "right_0"
            ReqOut:
              Difficulty: easy
              Or:
                - Dashes: one
                  Difficulty: normal
      - Room: "up_1"
        Holes:
          - Side: Up
            Idx: 1
            Kind: none
      - Room: "up_2"
        Holes:
          - Side: Up
            Idx: 2
            Kind: none
      - Room: "up_3"
        Holes:
          - Side: Up
            Idx: 3
            Kind: none
      - Room: "up_4"
        Holes:
          - Side: Up
            Idx: 4
            Kind: none
      - Room: "up_5"
        Holes:
          - Side: Up
            Idx: 5
            Kind: none
      - Room: "down_0"
        Holes:
          - Side: Down
            Idx: 0
            Kind: none
      - Room: "right_0"
        Holes:
          - Side: Right
            Idx: 0
            Kind: out
      - Room: "right_1"
        Holes:
          - Side: Right
            Idx: 1
            Kind: none
      - Room: "right_2"
        Holes:
          - Side: Right
            Idx: 2
            Kind: none
    InternalEdges:
      - To: "right_0"
        ReqOut:
          Difficulty: easy
          Or:
            - Dashes: one
              Difficulty: normal
  - Room: "6"
    Subrooms:
      - Room: "left_0"
        Holes:
          - Side: Left
            Idx: 0
            Kind: in
      - Room: "left_1"
        Holes:
          - Side: Left
            Idx: 1
            Kind: none
      - Room: "left_2"
        Holes:
          - Side: Left
            Idx: 2
            Kind: none
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Tweaks:
      - ID: 122
        Update:
          Remove: true
      - Name: "blackGem"
        Update:
          Add: true
          X: 208
          Y: 32
